### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/multishot#21]
`multishot -u http://staging.leanin.org -o .`

Here's what I get back:
![2013103-full](https://f.cloud.github.com/assets/27936/1262474/55a715e8-2c3f-11e3-849a-a79c077c2a40.png)

**Comment by jgallen23** [comment]
still having the issue: `/bin/multishot -u http://leanin.org`

![2013103-full](https://f.cloud.github.com/assets/27936/1262680/55eddbc4-2c42-11e3-8315-538116f7395b.png)

**Comment by dawnerd** [comment]
What path does it show in the template.html file? (Should be in /tmp/multishot)

**Comment by jgallen23** [comment]
`{{this.group}}/{{this.index}}-full.png`
