### ISSUE TITLE
Don't exit(1)

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/multishot#29]
https://github.com/firstandthird/multishot/blob/master/lib/screenshot.js#L29

When running grunt on my linux box, it exits early because there is no webkit2png.

You should only check if Screenshot() is called and return an error rather than killing the app. 

@dawnerd can you fix this ASAP?

**Comment by dawnerd** [comment]
Couple options here. We can have it throw an error, print the error then return from the function, or return the error text.

I prefer throwing the error since it's the more correct way to go about this.

**Comment by jgallen23** [comment]
If screenshots fn is async, it should return an error as first param. If it's sync, then throw it

**Comment by dawnerd** [comment]
It's half. Events are triggered when the screenshot service is done doing everything. Screenshot() itself doesn't take a callback or anything. Maybe have it trigger an error event instead?

**Comment by jgallen23** [comment]
Error event is perfect. Cli can watch that and let user know

**Comment by dawnerd** [comment]
To make the error event actually work had to move some of the init code into a .start() method. There shouldn't be any side effects in the cli other than actually getting errors reported.

**Comment by dawnerd** [comment]
Should also mention that grunt-multishot will have to be updated as well.

**Comment by jgallen23** [comment]
yea.  We should do a 0.x.0 release for both

**Comment by jgallen23** [comment]
can you create a pull req for this?
