### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/multishot#6]
good idea from @apermanentwreck: add the ability to group urls.  Each group should be on a new line in the image.

for the text file, maybe an extra line break means a group

**Comment by ghost** [comment]
Maybe allow a name for the group, so you can easily recognize, print out that group someone on the page.

**Comment by dawnerd** [comment]
+1 Pretty easy with imagemagick as it supports groups.

**Comment by jgallen23** [comment]
could put the group names on the far left side, maybe vertically.

![5bafvs1hw2-1200x1200](https://f.cloud.github.com/assets/27936/1083466/e731b1ba-1599-11e3-854e-38694e41da47.jpeg)

**Comment by jgallen23** [comment]
not sure why that uploaded sideways...

**Comment by ghost** [comment]
You could color code the groups, putting a colored border around the image, and print out a legend somewhere at the top left.
